const https=require('https'),crypto=require('crypto');
function config(){const keys=['WX_APPID','WX_MCHID','WX_SERIAL','WX_PRIVATE_KEY','WX_PAY_PUBLIC_KEY','WX_PAY_PUBLIC_KEY_ID','WX_API_V3_KEY','WX_NOTIFY_URL'];const missing=keys.filter(k=>!process.env[k]);if(missing.length)throw new Error('正式微信支付尚未配置，暂不可下单');return Object.fromEntries(keys.map(k=>[k,process.env[k].replace(/\n/g,'\n')]))}
function sign(text,key){return crypto.sign('RSA-SHA256',Buffer.from(text),key).toString('base64')}
function verify(headers,body,c){const h=Object.fromEntries(Object.entries(headers).map(([k,v])=>[k.toLowerCase(),v]));if(h['wechatpay-serial']!==c.WX_PAY_PUBLIC_KEY_ID)throw new Error('支付公钥ID不匹配');const time=Number(h['wechatpay-timestamp']);if(!Number.isFinite(time)||Math.abs(Date.now()/1000-time)>300)throw new Error('支付响应已过期');const msg=`${h['wechatpay-timestamp']}\n${h['wechatpay-nonce']}\n${body}\n`;if(!crypto.verify('RSA-SHA256',Buffer.from(msg),c.WX_PAY_PUBLIC_KEY,Buffer.from(h['wechatpay-signature']||'','base64')))throw new Error('支付签名无效')}
function request(method,path,payload){const c=config(),body=payload?JSON.stringify(payload):'',time=String(Math.floor(Date.now()/1000)),nonce=crypto.randomBytes(16).toString('hex');const signature=sign(`${method}\n${path}\n${time}\n${nonce}\n${body}\n`,c.WX_PRIVATE_KEY);const authorization=`WECHATPAY2-SHA256-RSA2048 mchid="${c.WX_MCHID}",nonce_str="${nonce}",timestamp="${time}",serial_no="${c.WX_SERIAL}",signature="${signature}"`;return new Promise((resolve,reject)=>{const req=https.request({hostname:'api.mch.weixin.qq.com',path,method,headers:{Authorization:authorization,Accept:'application/json','Content-Type':'application/json','Wechatpay-Serial':c.WX_PAY_PUBLIC_KEY_ID}},res=>{let text='';res.on('data',b=>text+=b);res.on('end',()=>{try{verify(res.headers,text,c);const result=text?JSON.parse(text):{};if(res.statusCode<200||res.statusCode>=300){const err=new Error(result.message||'微信支付请求失败');err.code=result.code;throw err}resolve(result)}catch(e){reject(e)}})});req.on('error',reject);req.setTimeout(15000,()=>req.destroy(new Error('支付请求超时，请刷新订单状态')));req.end(body)})}
async function create(o){const c=config();const r=await request('POST','/v3/pay/transactions/jsapi',{appid:c.WX_APPID,mchid:c.WX_MCHID,description:'商品订单',out_trade_no:o.id,notify_url:c.WX_NOTIFY_URL,time_expire:new Date(o.expiresAt).toISOString(),amount:{total:o.total,currency:'CNY'},payer:{openid:o._openid}});const timeStamp=String(Math.floor(Date.now()/1000)),nonceStr=crypto.randomBytes(16).toString('hex'),pkg='prepay_id='+r.prepay_id;return {timeStamp,nonceStr,package:pkg,signType:'RSA',paySign:sign(`${c.WX_APPID}\n${timeStamp}\n${nonceStr}\n${pkg}\n`,c.WX_PRIVATE_KEY)}}
function query(id){const c=config();return request('GET',`/v3/pay/transactions/out-trade-no/${encodeURIComponent(id)}?mchid=${encodeURIComponent(c.WX_MCHID)}`)}
function close(id){const c=config();return request('POST',`/v3/pay/transactions/out-trade-no/${encodeURIComponent(id)}/close`,{mchid:c.WX_MCHID})}
function decode(event){const c=config();if(typeof event.body!=='string')throw new Error('回调必须保留原始请求体');const body=event.isBase64Encoded?Buffer.from(event.body,'base64').toString('utf8'):event.body;verify(event.headers||{},body,c);const resource=JSON.parse(body).resource;if(!resource||resource.algorithm!=='AEAD_AES_256_GCM')throw new Error('回调算法无效');const ciphertext=Buffer.from(resource.ciphertext,'base64'),decipher=crypto.createDecipheriv('aes-256-gcm',Buffer.from(c.WX_API_V3_KEY),Buffer.from(resource.nonce));decipher.setAAD(Buffer.from(resource.associated_data||''));decipher.setAuthTag(ciphertext.subarray(-16));return JSON.parse(Buffer.concat([decipher.update(ciphertext.subarray(0,-16)),decipher.final()]).toString('utf8'))}
module.exports={config,verify,sign,create,query,close,decode};
