const test=require('node:test'),assert=require('node:assert/strict');
const seed=require('../miniprogram/data/products'),assets=require('../miniprogram/data/image-assets');
const storage=new Map();let preview,navigation,toast,failPreview=false,copies=0;
global.wx={getStorageSync:k=>storage.get(k),setStorageSync:(k,v)=>storage.set(k,v),env:{USER_DATA_PATH:'wxfile://usr'},getFileSystemManager:()=>({copyFile:o=>{copies++;o.success()}}),previewImage:o=>{preview=o;failPreview?o.fail(new Error('test')):o.success()},navigateTo:o=>{navigation=o.url},redirectTo:o=>{navigation=o.url},showToast:o=>{toast=o.title}};
const images=require('../miniprogram/utils/product-images'),makePage=require('../miniprogram/utils/detail-page');
function page(root){const p=makePage(root);p.data={...p.data};p.setData=function(value,callback){Object.assign(this.data,value);if(callback)callback()};return p}
test('legacy detail routes and direct picture taps use the correct image package',()=>{const id='demo-001',root=assets[id].root;const p=page('');p.onLoad({id});assert.equal(navigation,`/${root}/detail/index?id=demo-001`);images.openPreview(id);assert.equal(navigation,`/${root}/detail/index?id=demo-001&preview=1`);assert.equal(images.assetFor('__proto__'),null)});
test('detail uses larger gallery, previews the tapped image and preserves old stock and prices',async()=>{const multi=seed.find(p=>p.gallery.length>1),root=assets[multi.id].root;const p=page(root);p.id=multi.id;const old=JSON.parse(JSON.stringify(seed));old.find(p=>p.id===multi.id).skus[0].stock=2;old.find(p=>p.id===multi.id).skus[0].price=1234;storage.set('guzi.template.demo.v1',{products:old,orders:[{id:'existing'}]});await p.reload();assert.deepEqual(p.data.gallery,assets[multi.id].gallery);await p.preview({currentTarget:{dataset:{index:1}}});assert.ok(preview.current.startsWith('wxfile://usr/'));assert.ok(preview.current.endsWith(assets[multi.id].gallery[1].replace(/[^a-zA-Z0-9._-]/g,'_')));assert.equal(preview.urls.length,assets[multi.id].gallery.length);assert.equal(p.data.sku.stock,2);assert.equal(p.data.sku.price,1234);assert.equal(p.data.price,'6.17');assert.equal(storage.get('guzi.template.demo.v1').orders[0].id,'existing');failPreview=true;await p.preview({currentTarget:{dataset:{index:1}}});failPreview=false;assert.match(toast,/预览失败/)});
test('automatic preview opens larger image; missing photos stay marked and remote photos are respected',async()=>{storage.clear();preview=null;const p=page(assets['demo-001'].root);p.id='demo-001';p.autoPreview=true;await p.reload();assert.ok(preview.current.endsWith('demo-001-A.jpg'));assert.ok(preview.current.startsWith('wxfile://usr/'));assert.equal(p.autoPreview,false);preview=null;const missing=seed.find(p=>p.image.endsWith('placeholder.jpg')),empty=page('');empty.id=missing.id;await empty.reload();await empty.preview({currentTarget:{dataset:{index:0}}});assert.equal(preview,null);assert.match(toast,/还没有图片/);assert.deepEqual(images.galleryFor({...seed[0],image:'https://shop.example/product.jpg',gallery:['https://shop.example/product.jpg']},assets['demo-001'].root),['https://shop.example/product.jpg'])});

test('preview caches copied package images and does not copy remote product photos',async()=>{const before=copies;await images.previewGallery(assets['demo-001'].gallery,0);assert.equal(copies,before);await images.previewGallery(['https://shop.example/other.jpg'],0);assert.equal(copies,before);assert.equal(preview.current,'https://shop.example/other.jpg')});
