const privacy=require('../miniprogram/utils/privacy');
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const copy=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x)),local=new Map();
global.wx={getStorageSync:k=>copy(local.get(k)),setStorageSync:(k,v)=>local.set(k,copy(v)),removeStorageSync:k=>local.delete(k),showToast(){},showModal:o=>o.success({confirm:true}),navigateBack(){},navigateTo(){},switchTab(){}};
const s=require('../miniprogram/utils/store'),inventory=require('../miniprogram/utils/inventory');
s.config.demoAdminEnabled=true; // Test-only shop-manager view.
s.config.shippingFee=800; // Test-only configured postage.
const a={name:'测试收货人',phone:'13900000000',region:['示例市','示例市','示例区'],detail:'示例路演示楼100号'};
const patch={skuId:'demo-001-default',priceCents:1200,stockDelta:3,active:true};
test('address migration, selection, default, edit and deletion preserve order snapshots',async()=>{local.clear();privacy.acceptConsent(true);wx.setStorageSync('address.v1',a);const legacy=s.address();assert.equal(legacy.id,'legacy-default');const other=s.saveAddress({...a,name:'第二收货人'},{isDefault:true});assert.equal(s.addresses().length,2);assert.equal(s.address().id,other.id);s.chooseAddress(legacy.id);assert.equal(s.address().name,a.name);const order=await s.createOrder([{skuId:'demo-001-default',qty:1}],s.address(),'address-snapshot');s.saveAddress({...a,name:'已修改'},{id:legacy.id});assert.equal((await s.order(order.id)).address.name,a.name);s.deleteAddress(other.id);assert.equal(s.addresses()[0].isDefault,true);s.deleteAddress(legacy.id);assert.equal(s.address(),null);assert.equal(s.addresses().length,0);assert.equal((await s.order(order.id)).address.name,a.name)});
test('inventory changes cannot erase order reservation and request retries do not restock twice',async()=>{local.clear();privacy.acceptConsent(true);const order=await s.createOrder([{skuId:'demo-001-default',qty:2}],a,'reserved-stock');await s.updateProduct('demo-001',patch,'restock-once');await s.updateProduct('demo-001',patch,'restock-once');assert.equal((await s.catalog()).find(p=>p.id==='demo-001').stock,11);assert.equal((await s.order(order.id)).lines[0].price,500);await assert.rejects(()=>s.updateProduct('demo-001',{...patch,stockDelta:4},'restock-once'));await s.action(order.id,'cancel');assert.equal((await s.catalog()).find(p=>p.id==='demo-001').stock,13);await s.updateProduct('demo-001',{...patch,active:false,stockDelta:0},'hide-product');assert.ok(!(await s.catalog()).some(p=>p.id==='demo-001'));assert.ok((await s.adminProducts()).find(p=>p.id==='demo-001').needsReview);await assert.rejects(()=>s.createOrder([{skuId:patch.skuId,qty:1}],a,'hidden-product-order'),/下架/)});
test('price and stock validation reject floating fractions, negative inventory and malicious fields',()=>{for(const v of ['0','-1','1e3','0.001','NaN','9999999','1.'])assert.throws(()=>inventory.cents(v));assert.equal(inventory.cents('12.30'),1230);const p={id:'p',active:true,needsReview:true,skus:[{id:'s',price:100,stock:2}]};const input={skuId:'s',priceCents:1230,stockDelta:-2,active:false};const updated=inventory.patchProduct(p,input);assert.equal(updated.skus[0].stock,0);assert.equal(p.skus[0].stock,2);assert.equal(updated.needsReview,true);for(const field of [{stockDelta:-3},{stockDelta:1.1},{stockDelta:10001},{priceCents:NaN},{priceCents:-1},{active:'true'},{skuId:'unknown'}])assert.throws(()=>inventory.patchProduct(p,{...input,...field}))});
test('demo pagination returns all orders beyond 100 and status filtering applies before slicing',async()=>{local.clear();privacy.acceptConsent(true);const product=(await s.adminProducts())[0];const orders=Array.from({length:121},(_,i)=>({id:'DTEST'+String(i).padStart(4,'0'),status:i%2?'paid':'pending',createdAt:i,lines:[],total:100}));wx.setStorageSync('guzi.template.demo.v1',{products:[product],orders});let offset=0,all=[];for(;;){const page=await s.orderPage({offset});all.push(...page.orders);if(!page.hasMore)break;offset=page.nextOffset}assert.equal(all.length,121);assert.equal(new Set(all.map(o=>o.id)).size,121);const filtered=await s.orderPage({offset:20,status:'paid'});assert.equal(filtered.orders.length,20);assert.ok(filtered.orders.every(o=>o.status==='paid'))});
function loadPage(name){let p;global.Page=x=>p=x;const file=require.resolve('../miniprogram/pages/'+name+'/index.js');delete require.cache[file];require(file);p.data=copy(p.data);p.setData=function(x){Object.assign(this.data,copy(x))};return p}
test('order UI discards an old response when the customer changes status',async()=>{const original=s.orderPage;const pending=[];s.orderPage=opts=>new Promise(resolve=>pending.push({opts,resolve}));try{const page=loadPage('orders'),first=page.reload();const second=page.filter({currentTarget:{dataset:{id:'paid'}}});pending[1].resolve({orders:[{id:'paid-new',status:'paid',createdAt:1,total:100,lines:[]}],hasMore:false,nextOffset:20});await second;pending[0].resolve({orders:[{id:'pending-old',status:'pending',createdAt:1,total:100,lines:[]}],hasMore:true,nextOffset:20});await first;assert.deepEqual(page.data.orders.map(o=>o.id),['paid-new']);assert.equal(page.data.loading,false)}finally{s.orderPage=original}});
function backendHarness(){
 const collections={products:new Map([['demo-001',{_id:'demo-001',id:'demo-001',active:true,needsReview:true,skus:[{id:'demo-001-default',price:1000,stock:8}]}]]),orders:new Map([['ORDER001',{_id:'ORDER001',id:'ORDER001',_openid:'owner',status:'paid',createdAt:1,total:1000,lines:[]}]]),inventory_changes:new Map()};
 const command={in:values=>({$in:values}),lt:value=>({$lt:value})};
 function collection(name,source=collections){const map=source[name];return {doc(id){return {async get(){if(!map.has(id))throw new Error('document not exist');return {data:copy(map.get(id))}},async update({data}){if(!map.has(id))throw new Error('document not exist');map.set(id,{...map.get(id),...copy(data)})},async set({data}){map.set(id,{...copy(data),_id:id})}}},where(filter){let offset=0,limit=100,sort=[];const query={orderBy(k,d){sort.push([k,d]);return query},skip(n){offset=n;return query},limit(n){limit=n;return query},async get(){let rows=[...map.values()].filter(o=>Object.entries(filter).every(([k,v])=>v&&v.$in?v.$in.includes(o[k]):v&&v.$lt!==undefined?o[k]<v.$lt:o[k]===v));rows.sort((a,b)=>{for(const [k,d] of sort){const delta=a[k]>b[k]?1:a[k]<b[k]?-1:0;if(delta)return d==='desc'?-delta:delta}return 0});return {data:copy(rows.slice(offset,offset+limit))}}};return query}}}
 const db={command,collection,async runTransaction(fn){const source=Object.fromEntries(Object.entries(collections).map(([k,v])=>[k,new Map([...v].map(([id,o])=>[id,copy(o)]))]));const result=await fn({collection:name=>collection(name,source)});for(const k of Object.keys(collections))collections[k]=source[k];return result}};
 let openid='visitor';const cloud={DYNAMIC_CURRENT_ENV:'test',init(){},database:()=>db,getWXContext:()=>({OPENID:openid})},env={ADMIN_OPENIDS:'admin'};
 const sandbox={exports:{},require:n=>n==='wx-server-sdk'?cloud:n.startsWith('./')?require(path.resolve(__dirname,'../cloudfunctions/commerce',n)):require(n),process:{env},console};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../cloudfunctions/commerce/index.js'),'utf8'),sandbox);
 return {main:sandbox.exports.main,collections,env,as(value){openid=value}};
}
test('cloud enforces administrator and owner boundaries, verifies shipping config and records idempotent inventory changes',async()=>{const h=backendHarness();assert.equal((await h.main({action:'adminProducts'})).ok,false);assert.equal((await h.main({action:'updateProduct',id:'demo-001',patch,token:'cloud-save-once'})).ok,false);assert.equal((await h.main({action:'order',id:'ORDER001'})).ok,false);assert.equal((await h.main({action:'shippingPolicy'})).data.shippingFee,500);h.env.FREE_SHIPPING_CENTS='0';h.env.SHIPPING_FEE_CENTS='0';assert.equal((await h.main({action:'shippingPolicy'})).data.shippingFee,0);h.as('admin');assert.equal((await h.main({action:'order',id:'ORDER001'})).ok,true);for(let i=0;i<2;i++)assert.equal((await h.main({action:'updateProduct',id:'demo-001',patch,token:'cloud-save-once'})).ok,true);assert.equal(h.collections.products.get('demo-001').skus[0].stock,11);assert.equal(h.collections.inventory_changes.size,1);assert.equal(h.collections.products.get('demo-001').needsReview,true);assert.equal((await h.main({action:'updateProduct',id:'demo-001',patch:{...patch,stockDelta:-12},token:'invalid-stock'})).ok,false);assert.equal(h.collections.products.get('demo-001').skus[0].stock,11);h.as('owner');assert.equal((await h.main({action:'order',id:'ORDER001'})).ok,true);assert.equal((await h.main({action:'orderPage',offset:-1})).ok,false);assert.equal((await h.main({action:'orderPage',status:'paid'})).data.orders.length,1);h.as('visitor');assert.equal((await h.main({action:'orderPage',status:'paid'})).data.orders.length,0);assert.equal((await h.main({action:'createOrder'})).ok,false)});

test('cloud pickup preparation and redemption are administrator-only and require the correct code',async()=>{const h=backendHarness();h.collections.orders.set('PICKUP001',{_id:'PICKUP001',id:'PICKUP001',_openid:'owner',deliveryMode:'pickup',status:'paid',createdAt:1,total:500,lines:[]});h.as('owner');assert.equal((await h.main({action:'preparePickup',id:'PICKUP001'})).ok,false);h.as('admin');assert.equal((await h.main({action:'ship',id:'PICKUP001',carrier:'测试快递',tracking:'TEST12345'})).ok,false);const prepared=await h.main({action:'preparePickup',id:'PICKUP001'});assert.equal(prepared.ok,true);assert.match(prepared.data.pickupCode,/^\d{6}$/);assert.equal((await h.main({action:'completePickup',id:'PICKUP001',pickupCode:'wrong'})).ok,false);assert.equal(h.collections.orders.get('PICKUP001').status,'ready_pickup');h.as('owner');assert.equal((await h.main({action:'completePickup',id:'PICKUP001',pickupCode:prepared.data.pickupCode})).ok,false);h.as('admin');assert.equal((await h.main({action:'completePickup',id:'PICKUP001',pickupCode:prepared.data.pickupCode})).data.status,'completed');assert.equal((await h.main({action:'completePickup',id:'PICKUP001',pickupCode:prepared.data.pickupCode})).ok,false)});

test('cloud shipping settings default to confirmed postage and reject invalid overrides',async()=>{const h=backendHarness();let policy=(await h.main({action:'shippingPolicy'})).data;assert.equal(policy.shippingFee,500);assert.equal(policy.freeShipping,6900);h.env.SHIPPING_FEE_CENTS='';assert.equal((await h.main({action:'shippingPolicy'})).data.shippingFee,500);for(const fee of ['abc','-1','1.5']){h.env.SHIPPING_FEE_CENTS=fee;assert.equal((await h.main({action:'shippingPolicy'})).ok,false)}h.env.SHIPPING_FEE_CENTS='500';policy=(await h.main({action:'shippingPolicy'})).data;const d=require('../cloudfunctions/commerce/domain');for(const [price,fee] of [[13798,500],[13800,0],[13802,0]]){const q=d.quote([{id:'p',name:'测试商品',active:true,skus:[{id:'sku',price,stock:1}]}],[{skuId:'sku',qty:1}],policy);assert.equal(q.shippingFee,fee);assert.equal(q.total,q.subtotal+fee)}});
