const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const copy=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x)),storage=new Map();let reads=[],writes=[],destination='';
global.wx={getStorageSync:k=>{reads.push(k);return copy(storage.get(k))},setStorageSync:(k,v)=>{writes.push(k);storage.set(k,copy(v))},removeStorageSync:k=>storage.delete(k),showToast(){},showModal:o=>o.success({confirm:true}),navigateTo:o=>{destination=o.url},switchTab:o=>{destination=o.url},navigateBack(){},redirectTo(){}};
const privacy=require('../miniprogram/utils/privacy'),s=require('../miniprogram/utils/store'),serverConsent=require('../cloudfunctions/commerce/consent-version');
const address={name:'测试收货人',phone:'13900000000',region:['示例市','示例市','示例区'],detail:'示例路演示楼100号'};
function reset(){storage.clear();reads=[];writes=[];destination='';delete wx.requirePrivacyAuthorize}
function page(name){let p;global.Page=x=>p=x;const file=require.resolve('../miniprogram/pages/'+name+'/index.js');delete require.cache[file];require(file);p.data=copy(p.data);p.setData=function(x){Object.assign(this.data,copy(x))};return p}
test('no consent means no address read, migration, save or order reservation; shopping still works',async()=>{reset();storage.set('address.v1',address);assert.deepEqual(s.addresses(),[]);assert.equal(s.address(),null);assert.ok(!reads.includes('address.v1'));assert.ok(!reads.includes('addresses.v2'));assert.throws(()=>s.saveAddress(address),/同意/);await assert.rejects(()=>s.createOrder([{skuId:'demo-001-default',qty:1}],address,'no-consent-order'),/同意/);assert.deepEqual(writes,[]);assert.equal((await s.catalog()).find(p=>p.id==='demo-001').stock,10);assert.equal((await s.orders()).length,0);s.add('demo-001-default',1);assert.equal(s.cart().length,1)});
test('unchecked consent, refusal and direct address handler calls never collect personal fields',async()=>{reset();const p=page('address');p.onLoad({select:'1'});assert.equal(p.data.privacyAccepted,false);assert.equal(p.data.editing,false);assert.equal(p.data.consentChecked,false);p.field({currentTarget:{dataset:{field:'phone'}},detail:{value:address.phone}});p.region({detail:{value:address.region}});p.add();assert.equal(p.data.phone,'');assert.deepEqual(p.data.region,[]);assert.equal(p.data.editing,false);await p.agreeToTerms();assert.equal(privacy.hasConsent(),false);assert.match(p.data.consentError,/勾选/);p.declineConsent();assert.equal(destination,'/pages/home/index');assert.deepEqual(writes,[])});
test('explicit consent enables address input and persists a versioned receipt before saving',async()=>{reset();const p=page('address');p.onLoad({select:'1'});p.consentDoc({currentTarget:{dataset:{page:'privacy'}}});assert.equal(destination,'/pages/privacy/index');assert.equal(privacy.hasConsent(),false);p.consentChecked({detail:{value:['agree']}});await p.agreeToTerms();assert.equal(p.data.privacyAccepted,true);assert.equal(p.data.editing,true);for(const field of ['name','phone','detail'])p.field({currentTarget:{dataset:{field}},detail:{value:address[field]}});p.region({detail:{value:address.region}});p.save();assert.equal(s.address().phone,address.phone);assert.equal(writes[0],'privacy.consent.v1');assert.ok(privacy.snapshot().acceptedAt>0);assert.equal(privacy.snapshot().privacyVersion,'2026-10-08');assert.ok(!JSON.stringify(privacy.snapshot()).includes(address.phone))});
test('denied platform authorization never records own consent or reveals the contact form',async()=>{reset();wx.requirePrivacyAuthorize=o=>o.fail();const p=page('address');p.onLoad({});p.consentChecked({detail:{value:['agree']}});await p.agreeToTerms();assert.equal(privacy.hasConsent(),false);assert.equal(p.data.privacyAccepted,false);assert.equal(p.data.editing,false);assert.match(p.data.consentError,/微信隐私授权/);assert.deepEqual(writes,[])});
test('checkout protects both pickup and delivery before consent without deducting stock',async()=>{reset();wx.setStorageSync('checkout.v1',[{skuId:'demo-001-default',qty:1}]);const p=page('checkout');p.onLoad({source:'buy'});await p.reload();assert.equal(p.data.privacyAccepted,false);assert.equal(p.data.address,null);await p.mode({currentTarget:{dataset:{mode:'pickup'}}});p.field({currentTarget:{dataset:{field:'pickupPhone'}},detail:{value:address.phone}});assert.equal(p.data.pickupPhone,'');await p.submit();assert.equal((await s.orders()).length,0);assert.equal((await s.catalog()).find(p=>p.id==='demo-001').stock,10);p.consentChecked({detail:{value:['agree']}});await p.agreeToTerms();p.field({currentTarget:{dataset:{field:'pickupName'}},detail:{value:address.name}});p.field({currentTarget:{dataset:{field:'pickupPhone'}},detail:{value:address.phone}});await p.submit();const o=(await s.orders())[0];assert.equal(o.deliveryMode,'pickup');assert.equal(o.shippingFee,0);assert.equal(o.privacyConsent.privacyVersion,'2026-10-08')});
test('old policy versions require renewed consent and revocation hides existing address data',()=>{reset();storage.set('privacy.consent.v1',{privacyVersion:'2026-10-07',termsVersion:'2026-10-07',acceptedAt:Date.now(),scope:'fulfillment'});assert.equal(privacy.hasConsent(),false);privacy.acceptConsent(true);s.saveAddress(address);const p=page('address');p.onLoad({});assert.equal(p.data.addresses.length,1);privacy.revoke();p.onShow();assert.equal(p.data.privacyAccepted,false);assert.deepEqual(p.data.addresses,[]);assert.equal(p.data.phone,'');assert.deepEqual(s.addresses(),[]);assert.ok(storage.has('addresses.v2'))});
test('personal-data clearing deletes trial contacts, orders and consent but keeps browsing data',async()=>{reset();privacy.acceptConsent(true);s.saveAddress(address);s.add('demo-001-default',1);s.toggleFavorite('demo-001');await s.createOrder([{skuId:'demo-001-default',qty:1}],address,'clear-private-order');s.clearPersonalData();assert.equal(privacy.hasConsent(),false);assert.ok(!storage.has('addresses.v2'));assert.ok(!storage.has('guzi.template.demo.v1'));assert.equal((await s.orders()).length,0);assert.equal((await s.catalog()).find(p=>p.id==='demo-001').stock,10);assert.equal(s.cart().length,1);assert.deepEqual(s.favorites(),['demo-001'])});
test('cloud consent validation rejects missing, stale or forged time receipts',()=>{reset();privacy.acceptConsent(true);const value=privacy.snapshot();assert.equal(serverConsent.validateConsent(value).privacyVersion,value.privacyVersion);for(const changed of [null,{...value,privacyVersion:'old'},{...value,termsVersion:'old'},{...value,scope:'all'},{...value,acceptedAt:'1'},{...value,acceptedAt:Date.now()+120000}])assert.throws(()=>serverConsent.validateConsent(changed),/同意/);const backend=fs.readFileSync(path.join(__dirname,'../cloudfunctions/commerce/index.js'),'utf8');assert.ok(backend.indexOf('consent.validateConsent(event.privacyConsent)')<backend.indexOf("if(process.env.ENABLE_CHECKOUT"))});
test('both collection pages reuse unchecked consent controls and expose readable document links',()=>{const template=fs.readFileSync(path.join(__dirname,'../miniprogram/templates/consent.wxml'),'utf8');assert.ok(template.includes('data-page="terms"'));assert.ok(template.includes('data-page="privacy"'));assert.ok(template.includes('checked="{{consentChecked}}"'));for(const name of ['address','checkout']){const wxml=fs.readFileSync(path.join(__dirname,'../miniprogram/pages',name,'index.wxml'),'utf8');assert.ok(wxml.includes('wx:if="{{!privacyAccepted}}"'));const p=page(name);for(const match of template.matchAll(/bind(?:tap|change)="([\w]+)"/g))assert.equal(typeof p[match[1]],'function')}});
test('customer trial hides management and refuses direct administration; cloud role lookup fails closed',async()=>{reset();const p=page('profile');await p.onShow();assert.equal(p.data.isAdmin,false);assert.equal(await s.isAdmin(),false);const admin=page('admin');await admin.reload();assert.deepEqual(admin.data.orders,[]);assert.match(admin.data.error,/管理权限/);await assert.rejects(()=>s.adminProducts(),/管理权限/);await assert.rejects(()=>s.updateProduct('demo-001',{},'no-admin-permission'),/管理权限/);const oldMode=s.config.mode,oldCall=wx.cloud;s.config.mode='cloud';try{wx.cloud={callFunction:async()=>({result:{ok:true,data:{isAdmin:false}}})};assert.equal(await s.isAdmin(),false);wx.cloud={callFunction:async()=>({result:{ok:true,data:{isAdmin:true}}})};assert.equal(await s.isAdmin(),true);wx.cloud={callFunction:async()=>{throw new Error('offline')}};p.setData({isAdmin:true});await p.onShow();assert.equal(p.data.isAdmin,false)}finally{s.config.mode=oldMode;wx.cloud=oldCall}});
