const test=require('node:test'),assert=require('node:assert/strict');
const copy=x=>x===undefined?undefined:JSON.parse(JSON.stringify(x)),storage=new Map();
global.wx={getStorageSync:k=>copy(storage.get(k)),setStorageSync:(k,v)=>storage.set(k,copy(v)),removeStorageSync:k=>storage.delete(k),showToast(){},showModal:o=>o.success({confirm:true}),navigateTo(){},navigateBack(){},redirectTo(){},switchTab(){}};
const s=require('../miniprogram/utils/store'),d=require('../miniprogram/utils/domain');
const policy={...s.config,shippingFee:800};
const product=price=>[{id:'product',name:'测试商品',active:true,image:'',skus:[{id:'sku',name:'原款',price,stock:99}]}];
const address={name:'测试收货人',phone:'13900000000',region:['示例市','示例市','示例区'],detail:'示例路演示楼100号'};
const pickup={deliveryMode:'pickup',pickupContact:{name:'测试取货人',phone:'13900000000'}};
test('50% discount is calculated once per unit, rounds to cents, and ignores client prices',()=>{const q=d.quote(product(1000),[{skuId:'sku',qty:2,price:1,discountBps:1}],policy);assert.equal(q.lines[0].originalPrice,1000);assert.equal(q.lines[0].price,500);assert.equal(q.originalSubtotal,2000);assert.equal(q.subtotal,1000);assert.equal(q.discountAmount,1000);assert.equal(q.total,1800);assert.equal(d.salePrice(15,policy.promotion),8);assert.equal(d.quote(product(15),[{skuId:'sku',qty:2}],policy).subtotal,16);assert.equal(d.salePrice(1000,{enabled:false}),1000)});
test('free shipping uses discounted subtotal: 68.99 charges postage, 69.00 and 69.01 are free',()=>{for(const [original,discounted,fee] of [[13798,6899,800],[13800,6900,0],[13802,6901,0]]){const q=d.quote(product(original),[{skuId:'sku',qty:1}],policy);assert.equal(q.subtotal,discounted);assert.equal(q.shippingFee,fee);assert.equal(q.total,discounted+fee)}assert.equal(d.quote(product(1000),[{skuId:'sku',qty:1}],policy,pickup).shippingFee,0)});
test('unknown low-value postage blocks delivery without taking stock; free-shipping and pickup quotes remain available',async()=>{storage.clear();assert.equal(s.config.shippingFee,null);await assert.rejects(()=>s.createOrder([{skuId:'demo-001-default',qty:1}],address,'unknown-delivery-fee'),/邮费/);assert.equal((await s.catalog()).find(p=>p.id==='demo-001').stock,10);assert.equal((await s.orders()).length,0);assert.equal(d.quote(product(13800),[{skuId:'sku',qty:1}],s.config).total,6900);const q=d.quote(product(1000),[{skuId:'sku',qty:1}],s.config,pickup);assert.equal(q.total,500)});
test('pickup needs only valid contact; formal pickup requires configured location and hours',()=>{assert.equal(d.validateFulfillment(pickup,null,s.config).address,null);assert.throws(()=>d.validateFulfillment(pickup,null,s.config,true),/地点和时间/);assert.throws(()=>d.validateFulfillment({...pickup,pickupContact:{name:'',phone:'123'}},null,{...s.config,pickupLocation:'测试店',pickupHours:'10:00-18:00'}),/姓名/);assert.throws(()=>d.quote(product(1000),[{skuId:'sku',qty:1}],policy,{deliveryMode:'fake'}),/配送/);assert.throws(()=>d.validateFulfillment(pickup,null,{...s.config,pickupEnabled:false}),/自取/)});
test('pickup lifecycle preserves activity price, requires correct code, and cannot pretend to ship or redeem twice',async()=>{storage.clear();const o=await s.createOrder([{skuId:'demo-001-default',qty:1}],null,'pickup-lifecycle',pickup);assert.equal(o.total,500);assert.equal(o.shippingFee,0);assert.equal(o.address,null);assert.equal(o.pickupContact.name,pickup.pickupContact.name);await s.pay(o);await assert.rejects(()=>s.action(o.id,'ship',{carrier:'测试快递',tracking:'TEST12345'}));const ready=await s.action(o.id,'preparePickup');assert.equal(ready.status,'ready_pickup');assert.match(ready.pickupCode,/^\d{6}$/);await assert.rejects(()=>s.action(o.id,'receive'));await assert.rejects(()=>s.action(o.id,'completePickup',{pickupCode:'wrong'}));assert.equal((await s.order(o.id)).status,'ready_pickup');await s.action(o.id,'completePickup',{pickupCode:ready.pickupCode});assert.equal((await s.order(o.id)).status,'completed');await assert.rejects(()=>s.action(o.id,'completePickup',{pickupCode:ready.pickupCode}));s.config.promotion.enabled=false;try{assert.equal((await s.order(o.id)).total,500);assert.equal((await s.order(o.id)).lines[0].price,500)}finally{s.config.promotion.enabled=true}});
function loadPage(name){let p;global.Page=x=>p=x;const file=require.resolve('../miniprogram/pages/'+name+'/index.js');delete require.cache[file];require(file);p.data=copy(p.data);p.setData=function(x){Object.assign(this.data,copy(x))};return p}
test('checkout switches from unknown-postage delivery to zero-postage pickup, and serializes the selected mode',async()=>{storage.clear();s.saveAddress(address);wx.setStorageSync('checkout.v1',[{skuId:'demo-001-default',qty:1}]);const page=loadPage('checkout');page.onLoad({source:'buy'});await page.reload();assert.match(page.data.shippingError,/邮费/);assert.equal(page.data.total,'—');await page.mode({currentTarget:{dataset:{mode:'pickup'}}});assert.equal(page.data.shippingError,'');assert.equal(page.data.subtotal,'5.00');assert.equal(page.data.shipping,'0.00');assert.equal(page.data.total,'5.00');await page.submit();const o=(await s.orders())[0];assert.equal(o.deliveryMode,'pickup');assert.equal(o.total,500);assert.equal(o.pickupContact.phone,address.phone)});
