const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('crypto');
const db=new Map();const copy=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
global.wx={getStorageSync:k=>copy(db.get(k)),setStorageSync:(k,v)=>db.set(k,copy(v)),removeStorageSync:k=>db.delete(k),showToast(){},showModal:o=>o.success({confirm:true}),navigateTo(){},navigateBack(){},redirectTo(){},switchTab(){},setClipboardData(){}};
const s=require('../miniprogram/utils/store'),d=require('../miniprogram/utils/domain');
s.config.shippingFee=800; // Explicit postage fixture for shipping-path tests; store setting remains unconfirmed.
const address={name:'测试收货人',phone:'13900000000',region:['示例市','示例市','示例区'],detail:'示例路演示楼100号'};
test('catalog imports source values and mapped images',async()=>{const p=await s.catalog();assert.equal(p.length,8);assert.equal(p.find(x=>x.id==='demo-001').skus[0].price,1000);assert.equal(p.find(x=>x.id==='demo-001').skus[0].stock,10);assert.equal(p.filter(x=>!x.image.endsWith('placeholder.jpg')).length,7);assert.equal(p.filter(x=>x.group==='盲盒').length,3);assert.equal(p.reduce((n,p)=>n+p.stock,0),59)});
test('server quote ignores forged price, merges identical SKU and checks shipping',async()=>{const p=await s.catalog(),items=[{skuId:'demo-001-default',qty:1,price:1},{skuId:'demo-001-default',qty:2}];const q=d.quote(p,items,s.config);assert.equal(q.lines.length,1);assert.equal(q.originalSubtotal,3000);assert.equal(q.subtotal,1500);assert.equal(q.discountAmount,1500);assert.equal(q.total,2300);const stocked=p.map(x=>x.id==='demo-001'?{...x,skus:x.skus.map(k=>({...k,stock:20}))}:x);const free=d.quote(stocked,[{skuId:'demo-001-default',qty:14}],s.config);assert.equal(free.total,7000);assert.equal(free.shippingFee,0)});
test('reject invalid quantities, missing SKU and invalid address',async()=>{const p=await s.catalog();for(const qty of [0,-1,1.1,100,'1',NaN])assert.throws(()=>d.quote(p,[{skuId:'demo-001-default',qty}],s.config));assert.throws(()=>d.quote(p,[{skuId:'not-a-sku',qty:1}],s.config));for(const skuId of ['__proto__','constructor'])assert.throws(()=>d.quote(p,[{skuId,qty:1}],s.config));assert.throws(()=>d.quote(p,[{skuId:'demo-001-default',qty:11}],s.config),/库存/);assert.throws(()=>d.validateAddress({...address,phone:'123'}));assert.throws(()=>d.validateAddress({...address,detail:'短'}))});
test('duplicate submission does not create second order or deduct stock twice',async()=>{db.clear();const o=await s.createOrder([{skuId:'demo-001-default',qty:2}],address,'idempotent-token');const again=await s.createOrder([{skuId:'demo-001-default',qty:2}],address,'idempotent-token');assert.equal(o.id,again.id);assert.equal((await s.orders()).length,1);assert.equal((await s.catalog()).find(p=>p.id==='demo-001').stock,8);await s.action(o.id,'cancel');assert.equal((await s.catalog()).find(p=>p.id==='demo-001').stock,10);await assert.rejects(()=>s.action(o.id,'cancel'));assert.equal((await s.catalog()).find(p=>p.id==='demo-001').stock,10)});
test('stock exhaustion rolls back without writing order',async()=>{db.clear();await assert.rejects(()=>s.createOrder([{skuId:'demo-001-default',qty:11}],address,'stock-overflow'),/库存/);assert.equal((await s.orders()).length,0);assert.equal((await s.catalog()).find(p=>p.id==='demo-001').stock,10)});
test('demo payment -> shipping -> receipt -> aftersale follows valid state transitions',async()=>{db.clear();const o=await s.createOrder([{skuId:'demo-001-default',qty:1}],address,'payment-token');await assert.rejects(()=>s.action(o.id,'receive'));await assert.rejects(()=>s.action(o.id,'ship',{carrier:'测试快递',tracking:'TEST123456'}));await s.pay(o);assert.equal((await s.order(o.id)).status,'paid');await assert.rejects(()=>s.action(o.id,'cancel'));await s.action(o.id,'ship',{carrier:'测试快递',tracking:'TEST123456'});await s.action(o.id,'receive');assert.equal((await s.order(o.id)).status,'completed');await s.action(o.id,'refund',{reason:'商品损坏申请售后'});assert.equal((await s.order(o.id)).status,'refund_requested')});
function loadPage(name){let instance;global.Page=p=>instance=p;const path=require.resolve('../miniprogram/pages/'+name+'/index.js');delete require.cache[path];require(path);instance.data=copy(instance.data||{});instance.setData=function(v){Object.assign(this.data,copy(v))};return instance}
test('native Page handlers execute browse, filter, detail, cart, address, checkout and order flow',async()=>{db.clear();const home=loadPage('home');await home.reload();assert.equal(home.data.visible.length,8);home.search({detail:{value:'示例作品甲'}});assert.ok(home.data.visible.every(p=>p.name.includes('示例作品甲')));const cat=loadPage('category');await cat.reload();cat.group({currentTarget:{dataset:{value:'盲盒'}}});assert.ok(cat.data.visible.every(p=>p.group==='盲盒'));const detail=loadPage('detail');detail.id='demo-001';await detail.reload();detail.add();const cart=loadPage('cart');await cart.reload();assert.equal(cart.data.total,'5.00');cart.checkout();s.saveAddress(address);const checkout=loadPage('checkout');checkout.onLoad({source:'cart'});await checkout.onShow();assert.equal(checkout.data.total,'13.00');await checkout.submit();assert.equal(s.cart().length,0);const o=(await s.orders())[0];const page=loadPage('order');page.onLoad({id:o.id});await page.reload();await page.pay();assert.equal(page.data.o.status,'paid');const orders=loadPage('orders');await orders.reload();assert.equal(orders.data.visible.length,1);const admin=loadPage('admin');await admin.reload();admin.setData({carrier:'测试快递',tracking:'TEST12345'});await admin.ship({currentTarget:{dataset:{id:o.id}}});assert.equal((await s.order(o.id)).status,'shipped')});
test('WeChat pay signatures reject spoofed, tampered, expired and mismatched responses',()=>{const pay=require('../cloudfunctions/commerce/pay');const pair=crypto.generateKeyPairSync('rsa',{modulusLength:2048});const key=pair.privateKey.export({type:'pkcs8',format:'pem'}),pub=pair.publicKey.export({type:'spki',format:'pem'});const time=String(Math.floor(Date.now()/1000)),nonce='test-nonce',body='{"trade_state":"SUCCESS"}';const signature=pay.sign(`${time}
${nonce}
${body}
`,key);const headers={'Wechatpay-Timestamp':time,'Wechatpay-Nonce':nonce,'Wechatpay-Serial':'PUB_KEY_ID_TEST','Wechatpay-Signature':signature};const config={WX_PAY_PUBLIC_KEY_ID:'PUB_KEY_ID_TEST',WX_PAY_PUBLIC_KEY:pub};assert.doesNotThrow(()=>pay.verify(headers,body,config));assert.throws(()=>pay.verify(headers,body+' ',config));assert.throws(()=>pay.verify({...headers,'Wechatpay-Signature':'WECHATPAY/SIGNTEST/fake'},body,config));assert.throws(()=>pay.verify({...headers,'Wechatpay-Timestamp':'1'},body,config));assert.throws(()=>pay.verify({...headers,'Wechatpay-Serial':'OTHER'},body,config));assert.throws(()=>pay.config(),/尚未配置/)});
